### ISSUE TITLE
Support for Font Awesome 5 Pro

### ISSUE THREAD

**Issue by antwertinger** [divio/djangocms-icon#14] opened 2019-01-09 15:14 UTC
I would like to use Font Awesome 5 Pro.
I saw that in Bootstrap-Iconpicker it is possible to specify the version of the iconset to be used e.g
`data-iconset-version="5.3.1_pro"`
I could not find a way to set the version in this plugin. Could you add this possibility?

**Comment by FinalAngel** [comment] 2019-01-10 07:15
Hello @antwertinger , there's no option to set the version number in the options of the [bootstrap-iconpicker](http://victor-valencia.github.io/bootstrap-iconpicker/).

We cannot include the pro versions of fontawesome directly into the open-source project so you would have to add the iconset as "custom" and adapt the admin file as listed in our [README](https://github.com/divio/djangocms-icon#custom-web-font-icons).

**Comment by FinalAngel** [comment] 2019-01-10 13:06
@antwertinger thanks I oversaw that setting. Currently this is not integrated. I'd be happy to review a PR adding such functionality :)

**Comment by antwertinger** [comment] 2019-02-13 13:00
@FinalAngel I will try to add the functionality.
Can it be that the plugin isn't working anymore. I started a new aldryn project and installed the djangomcms icon plugin. There are no icons loaded. Can you confirm that?
<img width="1413" alt="bildschirmfoto 2019-02-13 um 13 50 42" src="https://user-images.githubusercontent.com/576402/52713172-e67c0c80-2f96-11e9-949b-2191f15befaf.png">

**Comment by ochagnon** [comment] 2019-02-14 08:01
> There are no icons loaded.

I experience the exact same problem myself, I didn't even customized it. it's a default install

**Comment by FinalAngel** [comment] 2019-02-14 10:16
I can confirm the same behaviour, investigating @antwertinger @ochagnon

**Comment by FinalAngel** [comment] 2019-02-14 12:11
@ochagnon @antwertinger does the following PR fix the issue for you?
https://github.com/divio/djangocms-icon/pull/16

On Divio Cloud it is 1.2.1.0 (alpha branch), but you will need to remove the added files in your project first to get the latest (or test with a clean project)

**Comment by antwertinger** [comment] 2019-02-14 13:16
@FinalAngel thanks for the PR. Now it works fine. 

One more thing i noticed, If you select an icon, it is not displayed in the ckeditor. I found out that one of the problems is because of an empty i tag. Ckeditor removes all empty tags. I see in your explorer demo template that there are some ckeditor settings for not removing empty tags. But this ist not documented in the djangocms-icon plugin. The Second problem is that the selected css font library is not loaded in the ckeditor. Would it not be nice if everything works out of the box after the djangocms-icon "installation", or at least the documentation should be expanded, to get the icon plugin working.

**Comment by FinalAngel** [comment] 2019-02-14 14:55
@antwertinger I agree that it is not straight forward regarding the tag removal. However that documentation needs to be on CKEditor / djangocms-text-ckeditor. I'll try to add a readme entry about the behaviour.

**Comment by FinalAngel** [comment] 2019-02-14 14:58
If you want to show the correct css in CKEditor you need to adapt the settings of the addon on divio cloud:

https://github.com/divio/djangocms-text-ckeditor/blob/175a1a444de8ca1ba4742196cb83150d45b5c505/aldryn_config.py#L47

**Comment by antwertinger** [comment] 2019-02-14 19:54
okay thank you, 
everytime saving the list of css files in the divio cloud ckeditor settings a new dimension is added to the list.

'/static/css/base.css', 'https://use.fontawesome.com/releases/v5.3.1/css/all.css'
['["'/static/css/base.css\'", '"https://use.fontawesome.com/releases/v5.3.1/css/all.css"]']
['["[\'/static/css/base.css\'"', '"\'https://use.fontawesome.com/releases/v5.3.1/css/all.css\']"]']

**Comment by antwertinger** [comment] 2019-02-14 20:55
> @ochagnon @antwertinger does the following PR fix the issue for you?
> #16
> 
> On Divio Cloud it is 1.2.1.0 (alpha branch), but you will need to remove the added files in your project first to get the latest (or test with a clean project)

it does not work In my existing project after upgrading to the new alpha version. Which files must be deleted exactly?

**Comment by FinalAngel** [comment] 2019-02-15 08:06
@antwertinger all the files that would be present in:
https://github.com/divio/djangocms-icon/tree/master/djangocms_icon/

Such as static/*, templates/* from djangocms-icon

**Comment by antwertinger** [comment] 2019-02-15 14:07
@FinalAngel I removed all files and afterwards installed the icon plugin again, but it doesn't work for an existing cloud project. I compared the files with your PR and everything is identically. You can test it with my Divio cloud project "4EB WEBSITE".

**Comment by FinalAngel** [comment] 2019-02-18 07:41
@antwertinger I'll try to investigate tomorrow

**Comment by FinalAngel** [comment] 2019-02-19 10:13
I removed the following files from your project @antwertinger 

* templates/djangocms_icon
* templates/admin/djangocms_icon
* static/djangocms_icon

after that it worked.

**Comment by ochagnon** [comment] 2019-02-20 05:41
> does the following PR fix the issue for you?

somewhat, some icon don't display.

![screen shot 2019-02-20 at 13 22 40 2](https://user-images.githubusercontent.com/1025638/53068237-b8587880-3512-11e9-8f3a-d32a701c9868.png)

the left icon html is

```
<i class="fa fa-clock-o circle-icon fa-3x text-blue mt-3 mb-3" aria-hidden="true"  style="background:#e9e9e9"></i>
```

not sure what i'm doing wrong...

**Comment by ochagnon** [comment] 2019-02-20 05:55
I know why... I'm using fa5 but this wasn't set:

```
DJANGOCMS_ICON_SETS = [
    ('fontawesome5', 'fa', 'Font Awesome'),
]
```

Since I set it, no icons work anymore

**Comment by antwertinger** [comment] 2019-02-20 07:17
@ochagnon have you tried to install the Pull request #16 from @FinalAngel? If you use Divio Cloud there is an alpha version available for this issue.

Have you add the following code in your settings.py to display the icons in the ckeditor
```python
CKEDITOR_SETTINGS = {
    'stylesSet': 'default:/static/js/addons/ckeditor.wysiwyg.js',
    'contentsCss': [
        'https://use.fontawesome.com/releases/v5.3.1/css/all.css',
    ],
}
```

Have you added the asset.html file to your templates? `templates/admin/djangocms_icon/includes/assets.html`
With the following content?
```html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
```

**Comment by antwertinger** [comment] 2019-02-20 07:28
@ochagnon your clock icon on the frontend don't have a bootstrap 5 class e.g. fas, far or fal

> `html<i class="fa fa-clock-o circle-icon fa-3x text-blue mt-3 mb-3" aria-hidden="true"  style="background:#e9e9e9"></i>`

if you use the solid style `<i class="fas fa-clock"></i>`
the regular style `<i class="far fa-clock"></i>`
or the light style `<i class="fal fa-clock"></i>`

**Comment by ochagnon** [comment] 2019-02-20 07:55
I switched my `requirements.txt` to 

```
-e git://github.com/divio/djangocms-icon.git@81a1a6abbdbeaec1556b86079b8b3895cf1b3565#egg=djangocms-icon
```

settings:

```
DJANGOCMS_ICON_SETS = [
    ('fontawesome5', 'fa', 'Font Awesome'),
]

CKEDITOR_SETTINGS = {
    'stylesSet': 'default:/static/js/ckeditor.js',
    'contentsCss': ['https://use.fontawesome.com/releases/v5.7.2/css/all.css']
}
```

my `ckeditor.js` file is the same as the original, but the following changed:

```
CKEDITOR.dtd.$removeEmpty.span = 1;
```

and my base.html

```
    {% addtoblock "css" %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    {% endaddtoblock %}
```

and run:

```
pip uninstall djangocms-icon
pip install -r requirements.txt
rm -rf static
./manage.py collectstatic
```

now the icon render correctly, but in the admin i still have this


![screen shot 2019-02-20 at 14 01 15](https://user-images.githubusercontent.com/1025638/53069751-0a4fcd00-3518-11e9-8c42-f5f0e9b02272.png)

**Comment by FinalAngel** [comment] 2019-02-20 09:56
@ochagnon you also need to make sure fontawesome5 is loaded in the widget:
https://github.com/divio/djangocms-icon/blob/master/djangocms_icon/templates/admin/djangocms_icon/includes/assets.html#L1

**Comment by FinalAngel** [comment] 2019-02-20 09:56
The PR has been merged into master

**Comment by antwertinger** [comment] 2019-02-20 10:47
@ochagnon you load the wrong fontawesome 5 version "5.7.2". The latest supported Version by the polugin is "5.3.1"

your asset.html file should look like this
```html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
```

settings.py
```python
CKEDITOR_SETTINGS = {
    'stylesSet': 'default:/static/js/ckeditor.js',
    'contentsCss': ['https://use.fontawesome.com/releases/v5.3.1/css/all.css']
}
```

Ensure that in your ckeditor.js file the remove empty options are set, otherwise the editor removes all empty span and i tags
```javascript
CKEDITOR.dtd.$removeEmpty.span = 0;
CKEDITOR.dtd.$removeEmpty.i = 0;
```

**Comment by FinalAngel** [comment] 2019-03-13 15:51
This has now been released :)

**Closed by FinalAngel** 2019-03-13 15:51 UTC
Labels: needs patch, status: accepted
